### ISSUE TITLE
Doubt about the Teensy

### ISSUE THREAD

**Issue by antonio-emilio** [iorodeo/potentiostat#20]
Hi! 
First of all, I woul'd like to congrat all contributors of the project. I woul'd like to ask if anyone see's any problem of changing the microcontroller to a ESP32... I'm having some dificculties in finding the teensy module here in Brazil.

**Comment by iorodeo** [comment]
It might be possible to use the ESP32. However, I think the ESP32 has only an 8-bit DAC which would limit the resolution of the output voltages pretty severely (just 256 values).  Also, there is a known nonlinearity in the analog inputs -  described here https://www.esp32.com/viewtopic.php?t=2881    I think it is possible to calibrate this out to some extent, but only some of the full range is available. 

We do have a new version of the Rodeostat available now https://iorodeo.com/products/rodeostat  which uses the Adafruit Itsy Bitsy M4 Express https://www.adafruit.com/product/3800     This version has pretty much same capability as the Teensy 3.2 version. The one exception being it won't work with the multiplexer expansion kit as the Itsy Bitsy M4 Express doesn't have enough IO to interface the multiplexer.  Note, you can  just put an Itsy Bitsy on the Teensy version of the Rodeostat as there are a few differences - e.g.  the pinout, etc.    However, the analog design of the potentiostat is almost exactly the same.   In addition we also have a higher current version of the Itsy Bitsy M4 Rodeostat with +/- 10, 100, 1000, and 10,000uA current ranges which will be available soon.
