### ISSUE TITLE
Compilation Error for Firmware

### ISSUE THREAD

**Issue by calfredoPF** [iorodeo/potentiostat#21]
Cannot compile the firmware with Arduino version 2.10 Windows 11, it throws the following error : 
c:\Users\xxx\Documents\Arduino\potentiostat\firmware\libraries\potentiostat/ps_analog_subsystem.h:29:26:
error: 'eAnalogReference' does not name a type
29 |             static const eAnalogReference DefaultAnalogReference = AR_DEFAULT;

Please advise, thank you.

**Comment by iorodeo** [comment]
Are you building the firmware for the teensy 3.2 or the ItsyBitsy M4 Express?  

The error you are getting can occur is there is a mismatch between the dev board you have selected in  Arduino IDE and the #define option you have uncommented in the ps_hardware_defs.h file  in the firmware/libraries/potentiostat sub-directory.   In particular you will get this error if you have the Teensy 3.2 selected in the Arduino IDE while having one of the ItsyBitsy option uncommented in the ps_hardware_defs.h file.  Make sure the dev board you are building for matches the option you have commented in the ps_hardware_defs.h file.

**Comment by calfredoPF** [comment]
Thanks for your reply. I am indeed using Teensy3.2, could you advise how to
choose which teensy board to uncomment after commenting the ItsyBitsy
definition ?
    // #define HW0P2_TEENSY_10V_MICRO
    // #define HW0P1_TEENSY_10V_MICRO
    // #define HW0P1_TEENSY_10V_MILL24
    // #define HW0P1_TEENSY_10V_NANO
    // #define HW0P1_TEENSY_8V_MICRO
---
[image: photo]
*Christopher Alfredo*
Product Manager, PointFit Technology Limited

96351522 | ***@***.*** ***@***.***> |
Linkedin <https://www.linkedin.com/in/christopher-alfredo-895899265/>
*IMPORTANT: The contents of this email and any attachments are
confidential. They are intended for the named recipient(s) only. If you
have received this email by mistake, please notify the sender immediately
and do not disclose the contents to anyone or make copies thereof. *

**Comment by iorodeo** [comment]
You will want to choose this based on your hardware variant.  For example, if you you are using hardware variant V0.2 for teensy 3.2 you would select HW0P2_TEENSY_10V_MICRO.   

The  HW0P1 options  are for the older V0.1 hardware.   The most common would be HW0P1_TEENSY_10V_MICRO which is for the standard V0.1 version with the ± 1, 2, 5, 10V output ranges.  The HW0P1_TEENSY_8V_MICRO is for a V0.1 variant which has a different programmable gain amplifier for the output voltages with ± 1, 2, 4, 8V output ranges.  The remaining two options HW0P1_TEENSY_10V_NANO and HW0P1_TEENSY_10V_MILL24 are for  custom V0.1  hardware variants with nanoamp and milliamp current ranges.
