### ISSUE TITLE
More of a question: constant current mode?

### ISSUE THREAD

**Issue by dansteingart** [iorodeo/potentiostat#7]
Awesome project. Does the standard firmware and/or standard rodeostat hardware also support galvanostatic/constant current modes?

**Comment by iorodeo** [comment]
Not currently.   If it doesn't need to be too fast then it might be possible to do this is software using manual/direct mode with the Python API http://stuff.iorodeo.com/docs/potentiostat/getting_started.html#manual-direct-operation    You could write a feedback control loop which measures the current and adjusts the output voltage to keep it constant using the get_curr and set_volt methods.

**Comment by dansteingart** [comment]
Thanks.  I might try to build into the teensy firmware.
